### ISSUE TITLE
Add MutatedTransform to the input type for tmin & push mutational stage

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#1251]
like this https://github.com/AFLplusplus/LibAFL/blob/c8c5d89f336208112ff91889865e6bedb62aa23d/libafl/src/stages/mutational.rs#L97
in mutational stage

**Comment by tejas012321011** [comment]
I would like to contribute to it. Can you please explain to me in *some* detail, what you need me to do, and provide any starting references/resources that can help in contributing, if any?

**Comment by gerceboss** [comment]
Sorry , But I could not find `Input` types in the files you mentioned , instead I found the other types which were not generics as it is in the file you mentioned.
`<Self::State as UsesInput>::Input: HasLen + Hash` how do I add MutatedTransform here ? 
@tokatoka

**Comment by am009** [comment]
I have been investigating this issue and reading related codes these days.

The `MutatedTransform` is introduced in [this commit](https://github.com/AFLplusplus/LibAFL/commit/28786c943a20811a833ed4afb7978aa970df97bf) along with the Grimoire. [Grimoire](https://github.com/RUB-SysSec/grimoire) is a new fuzzing technique that can efficiently fuzz programs that require highly structured inputs (e.g., a programming language).

The [modifications](https://github.com/AFLplusplus/LibAFL/commit/28786c943a20811a833ed4afb7978aa970df97bf#diff-bed5bfe7499f6159e77c2638a61adaed60f91486e9d8f8926078d2ab704cb8e8L53-L73) to the mutational stage in the commit serves as a good reference. Previously, you get the testcase from the corpus, then convert it into input, mutate it using mutators, and execute it. Now with `MutatedTransform`, you use `try_transform_from` to convert from testcase to `MutatedTransform<Input, State>`, then pass it to mutators (mutators now mutate over a brand new type), and convert back to input using `try_transform_into` before execution. `try_transform_into` also returns a `MutatedTransformPost` callback that is called after new testcase is inserted into the corpus.

For example, [`type UnicodeInput = (BytesInput, StringIdentificationMetadata)`](https://github.com/AFLplusplus/LibAFL/blob/04d87ccc898c15ae554cbc727ce2a58a34aa015f/libafl/src/mutators/string.rs#L29) implemented `MutatedTransform<BytesInput, S>`. Besides byte array, it also contains additional metadata (`StringIdentificationMetadata`). When it is transformed from a Testcase (using `try_transform_from`), the metadata is fetched from the testcase and `UnicodeInput` is constructed. Then `UnicodeInput` is passed to mutators. Mutators can leverage the metadata to perform better mutations. After mutation and before execution, `UnicodeInput` is transformed back into `BytesInput` (using `try_transform_into`), and `StringIdentificationMetadata` is returned as `MutatedTransformPost`. When the new mutated input is interesting and is inserted into the corpus as a testcase, the post-callback is called to insert the corresponding metadata for the testcase.

For any other types that do not need such a mechanism, there is a [reflexive definition](https://github.com/AFLplusplus/LibAFL/blob/c6875b8cf6264dcde05833a7839755879aeff301/libafl/src/stages/mutational.rs#L58) that implements `MutatedTransform<I, S>` for `I`. It makes `try_transform_into` a no-operation, and mutators still mutate over `I` because now `I` is doubled as `MutatedTransform<I, S>`.
