### ISSUE TITLE
Libafl_libfuzzer: Timestamps are not preserved across crashes/timeouts

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1455]
If you launch the manager everytime, then the timestamp is not preserved across restarts

_Originally posted by @tokatoka in https://github.com/AFLplusplus/LibAFL/pull/981#discussion_r1301979782_

**Comment by tokatoka** [comment]
I think this happens also in non-libafl_libfuzzer fuzzer

**Comment by tokatoka** [comment]
without afl_exec_sec then execs/sec is broken.
because when the restart happens the last_window_time is updated here
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/monitors/mod.rs#L285

but the executions count adds the executions count before the restart.
so the time is since the restart. but the execution count is from the start of the fuzzing

**Comment by addisoncrump** [comment]
Do we just add that feature and it's fixed? :sweat_smile:

**Comment by tokatoka** [comment]
yes. but there's still something that I don't understand with this bug. I'll debug it tomorrow
