### ISSUE TITLE
Debugging with GDB fails if Launcher is used

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#148]
Previously while I not used the Launcher, the following `.gdbinit` config worked to debug the child process (program under test):

```
set follow-fork-mode child
set detach-on-fork off
```
(https://sourceware.org/gdb/onlinedocs/gdb/Forks.html)

Now with the Launcher this somehow stopped working. Somehow the client is no longer able to connect to the parent process:

```
[/home/max/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/de933fe/libafl/src/bolts/llmp.rs:2478] "Connection Refused.. Retrying" = "Connection Refused.. Retrying"
```

I suspect that the reason for this is the Launcher. Bug maybe this is also a newly introduced behavior.

**Comment by domenukk** [comment]
Hey, your issue is the `set detach-on-fork off`. According to the GDB docs, the other followed process remains "suspended until we switched to it using the `inferior` command and resumed it using the `continue` command."
So what happens is:
- launcher forks parent and 1st child
- gdb follows child, parent gets suspended
- child can't connect to the parent (as it's suspended)

Any reason in particular you set `detach-on-fork`? Either not set it (then your parent will continue running), or `set follow-fork-mode parent`, continue (and detach) the parent, then swap to the child.

My usual way to debug is to use catch points, specifically `catch fork`, then decide at that point if I want to follow the child or the parent.

Another option is to print the child pid and add a sleep to your first execution in the child, then attach to its pid.

**Comment by s1341** [comment]
FWIW, I debug launcher with gdb all the time. I am usually only interested in debugging the fuzzing client, in which case `set follow-fork-mode child` is sufficient.

**Comment by maxammann** [comment]
@s1341 oke very strange, this is not working for me, will take a closer look

**Comment by maxammann** [comment]
Oke my problem is not a GDB but an Clion problem. If I only do `set follow-fork-mode child` then my program crashes with a SIGABRT in libc: 

```
Thread 2.1 received signal SIGABRT, Aborted.
```

Using GDB directly works fine!
