### ISSUE TITLE
CI: depend on normal libafl build success before launching fuzzers

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2014]
Fuzzers are expensive to build/test. We should ensure that they are not run in CI unless the normal builds (ubuntu + no-std) complete successfully.

**Comment by tokatoka** [comment]
I think what we really need is an mechanism that stops any previous CI run when you push something onto the existing branch. Therefore, only one run per one PR.
There are usually at most 2 ~ 3 people working simultaneously. but the CI is slowed down because people don't usually cancel the previous run and free up the machines

**Comment by addisoncrump** [comment]
I think that's very reasonable anyways. Doc and clippy tests after build tests.

**Comment by tokatoka** [comment]
i separated the job

**Comment by tokatoka** [comment]
done
