### ISSUE TITLE
how to detect segfault of qemu_linux_process

### ISSUE THREAD

**Issue by juniorprincewang** [AFLplusplus/LibAFL#2626]
In the qemu_linux_process example, I try to test the segfault, however the fuzzer fails to observe the crash, the qemu instance continues to process.
So how to detect the segfault or timeout of QEMU linux process?

```
bool FuzzMe(const uint8_t *Data, size_t DataSize) {
  if (DataSize > 3) {
    if (Data[0] == 'F') {
      if (Data[1] == 'U') {
        if (Data[2] == 'Z') {
          if (Data[3] == 'Z') { *(char *)1 = 2; }
        }
      }
    }
  }

  return false;
}

int main() {
  // Prepare some space for the input
  uint8_t Data[10] = {0};

  lqprintf("Fuzzing starts\n");

  // Start fuzzer here
  size_t len = libafl_qemu_start_virt(Data, 10);

  // Call the target
  bool ret = FuzzMe(Data, len);

  libafl_qemu_end(LIBAFL_QEMU_END_OK);
}
```

**Comment by tokatoka** [comment]
doesn't timeout just work normally? you can just pass timeout to your executor

for segfault it is more difficult.
> however the fuzzer fails to observe the crash, the qemu instance continues to process.

It won't crash because the crash is observed inside your guest vm which won't be treated as the crash on your host.
What you can do is do like nyx
https://github.com/nyx-fuzz/packer/blob/6067e5c0ffb3e9aec35aa3aef29b3e390dd313bd/packer/linux_x86_64-userspace/src/misc/crash_handler.c#L74
You can install singalhandler for sigsegv or sigabrt and then inside your handler return `LIBAFL_QEMU_END_CRASH` when those errorneous signals are observed
