### ISSUE TITLE
Timeout for LLMP Clients

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#36]
`LLMP`, short for LowLevel Message Passing, has the concept of multiple clients, which are all connected to one broker.
The broker broadcasts each new message it receives from a client (over an individual shared) to all other clients via one ...shared... shared map.
So far, LLMP Clients never get unregistered.
It would be good to keep track of the last time a client sent a message, and unregister them accordingly.
This could be done in the `once` method of the broker (which is called in a loop in the broker)
https://github.com/AFLplusplus/LibAFL/blob/6e4c6a9b6b0db909853a19a68ba769bb2516f1bf/libafl/src/bolts/llmp.rs#L1349

On top, we may want to support a `good-bye`/`unregister` message from clients when they know they are done. This could be called inside a `Drop` crate automatically.

**Comment by Srg213** [comment]
Hello. 
I have made few changes to `LlmpBroker` struct to add `Vec<Duration>` so that the data is stored in `self` itself.
For testing the changes, i built the libfuzzer_libpng example as mentioned. But the following make command is throwing an error.
`make CC="$(pwd)/../target/release/libafl_cc" CXX="$(pwd)/../target/release/libafl_cxx" -j `nproc``

The error message is 
`thread 'main' panicked at 'Failed to run the wrapped compiler: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/bin/libafl_cc.rs:29:14`
I found that "$(pwd)/../target/release/libafl_cc" is a binary but not a directory. The exact path is - `fuzzers/libfuzzer_libpng/target/release/libafl_cc`. As per the instructions, I think I am building it in the correct directory. -` fuzzers/libfuzzer_libpng/libpng-1.6.37`.
Can you help me regarding this?

**Comment by tokatoka** [comment]
You can run `cargo make run` to get it working

**Comment by Srg213** [comment]
Actually I used that command first. Then to check where the build breaks, I followed instructions from `README.md`
Yet I tried it again today. It is still showing the same error.

**Comment by tokatoka** [comment]
Do you have clang installed?

**Comment by Srg213** [comment]
Really thanks for the help.
I have changed the struct LlmpBroker to add Vec<Instant> for keeping the last_msg_time_for_clients. For now I added a random time duration after which clients are removed. Here are the [changes](https://github.com/AFLplusplus/LibAFL/commit/e81b80c1b717352fba9731cd1e8b708e3726b931).
Can you specify the exact time duration? and regarding the following

> On top, we may want to support a good-bye/unregister message from clients when they know they are done. This could be called inside a Drop crate automatically.

I guess adding impl Drop for LlmpReceiver might be the correct way. Should I add this trait ?

**Comment by domenukk** [comment]
> Really thanks for the help. I have changed the struct LlmpBroker to add `Vec<Instant>` to store the `last_msg_time_for_clients`. For now I added a random time duration after which clients are removed. Here are the [changes](https://github.com/AFLplusplus/LibAFL/commit/e81b80c1b717352fba9731cd1e8b708e3726b931). If the above changes are fine, could I get a PR access?

I _think_ the changes are not enough - we may have to do more things to safely unmap, for example we may want to tell the client that we unmapped it, in case it is still alive. but it is a good start. You should just be able to open a PR, no need for any additional permissions(?)

Can you specify the exact time duration?

Let's do 30 seconds for now, we can adjust it later.

and regarding the following
> 
> > On top, we may want to support a good-bye/unregister message from clients when they know they are done. This could be called inside a Drop crate automatically.
> 
> I guess adding impl Drop for LlmpReceiver might be the correct way. Should I add this trait ?

Sounds good 👍

**Comment by Srg213** [comment]
Thanks for the advice.
To tell the client it is unmapped, a new message could be added on the shared map of the broker itself but it will broadcast to all clients. 
I am finding a way to send message specifically to that receiver which is going to be unmapped. 
This could be done in Drop trait or in the once function itself. 
Wait I think adding Drop trait for LlmpClient would be a lot simpler cause Llmpreceiver is a single channel.
Is this the correct approach?

**Comment by domenukk** [comment]
@Srg213 note that #1057 introduces a client timeout, it's not perfect (pages may not properly be cleaned up, client's don't notice when the broker is gone), but it's a start

**Comment by Srg213** [comment]
Okay. I see many changes done for timeout like last_msg_time is added in Receiver side. But as you said client's don't notice the broker gone and an unregister message for clients is not added ig.
Regarding cleaning the pages, would it be feasible to include a parameter to know when either sender or receiver is dropped so that the page could be dropped?
The commits include a lot of changes to the project. Thank you for bringing it to my notice.

**Comment by domenukk** [comment]
So the original concept (never implemented) was to set `sender_dead` to 1, here. I think it could make sense to introduce an (atomic) ref count how many users a page currently has, and clean up accordingly(?)
https://github.com/AFLplusplus/LibAFL/blob/0727c80347d13f5adc05c77228fb0d6dc7de8c41/libafl/src/bolts/llmp.rs#L785

I don't have a perfect answer handy, else I'd have implemented it :)

**Comment by Srg213** [comment]
yes adding atomic reference count Arc would make sense. In this case, I think we can create a iterative function to check if sender_dead == 1 which might call Drop trait on Llmppage and clean accordingly. This would incur runtime costs as we would have to check iteratively.
Or I guess we can introduce an additional wrapper object around Llmppage which has variable of type Arc::<Llmppage>. This could then be cloned as per the number of users. This will reduce the use of unsafe operations while referencing pages and can be easily dropped too. But it requires a lot of changes to the repo.

**Comment by domenukk** [comment]
Sounds good. A few things that come to my mind when thinking about it:
a) since we have multiple processes here, we may want to use atomic variables and count the references ourselves
b) For InProcessExecutor, a LLMP member may crash, and restart. During this time, the page would not be mapped, but we still don't want to drop it (which is fine if we refcount manually)
c) there might be multiple pages mapped by the sender, while each (of potentially multiple) receivers always only have one page mapped.
```
[         page 1                         ][           page 2                       ][           page 3                       ]
[^receiver reads this page. ][^only mapped by sender   ][^sender writes to this page]
```

**Comment by Srg213** [comment]
> * we may want to use atomic variables and count the references ourselves

Ok I see that's why there are less Arc instances in processes. 

> to introduce an (atomic) ref count how many users a page currently has,
I think timeout could be introduced to set sender_dead == 1(maybe in `prune_old_pages` fun). And many-to-one mapping of pages is based on sender, so dropping a page should depend on timeout of sender and maybe on users mapped to a page.

A client has both sender and receiver. Timeout for clients would include unmapping all pages of both sender and receiver.(?)

 Would cleaning the pages take into account the users mapped and then check for timeout or just the setting sender_dead for each page would suffice as every page has sender_id  ?

**Comment by Srg213** [comment]
Hi.
I have tried adding refcount to check the number of users mapped to a page. But I am not clear whether the pages are always pruned and reallocated.

- In `prune_old_pages `function, the sender prunes older pages and adds them to unused_shmem_cache to reallocate them. If a user is dropped, the page it is allocated is marked safe to unmap and then added to unused_shmem_cache to avoid freeing them.
The pages in `unused_shmem_cache` are only mapped by sender and so cannot be set to sender_dead==1.

- Say a field is added to check whether users are mapped or not, for ex. `sender_dead==1` then should the page be dropped or added for reallocating as the pages marked_safe_to_unmap are not dropped but are reallocated?

- `mark_safe_to_unmap` is set only when registering a client or adding a new client. In case of timeout, receiver are dropped from `llmp_clients` so I thought of marking it `safe to unmap` and then dropping it. But seeing the pages are reallocated if marked safe, should I add a new function to check if pages could be dropped?

- If I have interpreted this correctly, the steps would be to reduce refcount in case of timeout(now in `fn once`) and iterating to see the pages mapped by those users(?) before removing them .
