### ISSUE TITLE
edges_map_from_ptr can trigger undefined behaviour

### ISSUE THREAD

**Issue by jdm** [AFLplusplus/LibAFL#446]
https://github.com/AFLplusplus/LibAFL/blob/1608294d0baa70adcb70ebae80155331c015965c/libafl_targets/src/coverage.rs#L27-L32

edges_map_from_ptr returns a mutable borrow out of thin air. This means that it's possible to call this function multiple times and end up with multiple mutable borrows to the same underlying value, which is undefined behaviour. At minimum, this function should be marked unsafe to represent the caller's responsibility for avoiding this situation.

**Comment by domenukk** [comment]
Checking the way we use this function right now, there is this (potentially) concerning occurrence:
https://github.com/AFLplusplus/LibAFL/blob/1608294d0baa70adcb70ebae80155331c015965c/fuzzers/libfuzzer_libpng_ctx/src/lib.rs#L148

Here, we use the borrow in an observer that will (try to) read its contents from the map after each execution, but the changes happen by the target code (C) directly, accessing the raw pointer.
Since this is UB, I guess the compiler could prove that the map never gets written to from rust during borrow, and optimize all reads out (?)

**Comment by jdm** [comment]
I suspect a safer implementation would be to store the raw pointer and dereference it as necessary, rather than storing the mutable slice.

**Comment by domenukk** [comment]
Sounds doable, I'll take a look

**Comment by domenukk** [comment]
Done with 30eb150
