### ISSUE TITLE
MacOS Aarch64 ShMem (partially) broken

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#668]
**Describe the bug**

On aarch64, MacOS testcases fo ShMem fail right now

**Comment by domenukk** [comment]
Probably I had the Unix socket file still lying around somewhere, closing for now

**Comment by s1341** [comment]
Might be worth using an abstract socket name. That way there is no chance of leaving a socket file on disk.

**Comment by tokatoka** [comment]
I noticed today that forkserver's shared memory test case is not working.
I works if testcases are passed through filesystem, but not with shmem.

I got either signal 11 (sigsegv when accessing shmem memory to read testcases)
or 
the input is not passed correctly passed to the harness 
(I noticed this because with debug_child option, the input is not changed at all in each fuzzer execution, so I guess the shmem pointer is pointing to a wrong location)

**Comment by tokatoka** [comment]
ok it seems it does not work with AFLplusplus/afl-fuzz either.

**Comment by tokatoka** [comment]
closing as the problem does not seem to be from libafl
