### ISSUE TITLE
Test cases stored to disk should have globally unique file names

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#77]
Currently, we use names of the form `id_{}` to name test cases stored to disk using an `OnDiskCorpus`. 

We should change this behavior so that we have globally unique test case names. This can be achieved by combining some minimal metadata (such as timestamp, last mutator) with a hash of the test case input data.

**Comment by epi052** [comment]
Following up from this [discord thread](https://discord.com/channels/736989425770168422/848712494926659605/912834272392540181). 

I used https://github.com/vanhauser-thc/afl-cov against a libafl corpus created with [CachedOnDiskCorpus](https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/corpus/cached.rs#L21). My corpus directory contained files such as 

```
-rw-rw-r-- 1 epi epi       0 Nov 24 05:23 .56ee067d0349278e.lafl_lock
-rw-rw-r-- 1 epi epi      48 Nov 24 05:23 56ee067d0349278e
-rw-rw-r-- 1 epi epi       0 Nov 24 05:24 .bcfe2daeff605a1b.lafl_lock
-rw-rw-r-- 1 epi epi      79 Nov 24 05:24 bcfe2daeff605a1b
-rw-rw-r-- 1 epi epi       0 Nov 24 05:24 .97d8db7661588d1f.lafl_lock
-rw-rw-r-- 1 epi epi      22 Nov 24 05:24 97d8db7661588d1f
```

afl-cov is pretty opinionated about what it expects to find in its source directory, and its expectations don't jive with what libafl produces. [First, it expects to find a `source_dir/queue/FILES` style setup](https://github.com/vanhauser-thc/afl-cov/blob/master/afl-cov.sh#L24-L31). 

Second, it  expects all files to [begin with `id:`](https://github.com/vanhauser-thc/afl-cov/blob/master/afl-cov#L937-L938).

Third, it assumes the filename after `id:` is a [base 10 int](https://github.com/vanhauser-thc/afl-cov/blob/master/afl-cov#L345). 

I'm guessing there are more, but that's all i needed to deal with in order to get it working against my current setup. 

I give all the background to ask: which project should be updated? We could update afl-cov to be more forgiving, or update libafl's file naming scheme, or some combination.  

I'm down to put in a PR, once I know the direction to take.

> as an aside, the lock files don't get cleaned up on fuzzer shutdown, that could maybe get looked at in this issue as well, if it makes sense

**Comment by vanhauser-thc** [comment]
the files naming in libafl has to be changed to avoid collisions. but the afl naming is archaic and I dont think portable (does windows allow `:` in filenames?).
So I think changing afl-cov to be more forgiving is one action, and still naming the on-disk corpus to something collision free is another.

**Comment by epi052** [comment]
@s1341 @domenukk 
re: discussion in PR #392, this issue can be closed
